Changed ZooKeeper path to use table UUID
sazonov/flyway pull request #1
Opened 2023-11-16 14:38 UTC by estaine

2023-11-30 13:23 UTC, darkfrog26 commented
@sazonov any reservations with merging this into your branch?

2024-01-16 06:48 UTC, estaine commented
Hey, this PR moves Zookeeper path to a parameter. We use a {uuid} macros-based Zookeeper paths in order not to make an extra dependency between a table name and its path in Zookeper.
The default behaviour (when no config parameter is set) is left intact.

2024-01-16 07:22 UTC, sazonov requested changes

2024-01-16 07:22 UTC, sazonov commented on flyway-community-db-support/flyway-database-clickhouse/src/main/java/org/flywaydb/community/database/clickhouse/ClickHouseConfigurationExtension.java
> +    private static final String ZOOKEEPER_PATH = "flyway.zookeeper.path";
Let's change the constant to "flyway.clickhouse.zookeeperPath" besause it applies to ClickHouse only.

2024-01-16 07:22 UTC, sazonov commented on flyway-community-db-support/flyway-database-clickhouse/src/main/java/org/flywaydb/community/database/clickhouse/ClickHouseConfigurationExtension.java
> +        if ("FLYWAY_ZOOKEEPER_PATH".equals(environmentVariable)) {
FLYWAY_ZOOKEEPER_PATH -> FLYWAY_CLICKHOUSE_CLUSTER_NAME

2024-01-16 07:22 UTC, sazonov commented on flyway-community-db-support/flyway-database-clickhouse/src/main/java/org/flywaydb/community/database/clickhouse/ClickHouseDatabase.java
> +                engine = "ReplicatedMergeTree('" + zookeeperPath + "', '{replica}')";
'/clickhouse/tables/{shard}/{database}/{table}' this should be the default value for the new configuration param. I would suggest to set this value to ClickHouseConfigurationExtension::zookeeperPath as initial value so we keep current line for all cases and remove all redundant conditions.

2024-01-16 07:25 UTC, sazonov commented
@estaine thank you for the work.

2024-01-16 07:53 UTC, estaine commented
@sazonov Thank you so much for such a quick answer.
All your comments make sense and I've just updated my pull request

2024-01-16 08:59 UTC, merged